### PR TITLE
add-logo-animation/ translation-revision

### LINKED ISSUE #9: Add logo animation
When the page loads, at the top show "skp", then animate the appearing "eee" in between so that it becomes "skeeep".

### PR DESCRIPTION
**Pull request by e-caste**

### CODE REVIEW

**Comment by e-caste** [comment]
@itIsJim I don't see any changes related to the logo animation in your branch. Have you forgotten to push some commits or am I missing something?

**Comment by itIsJim** [comment]
you are right maybe i missed the commit on those parts. Should I push again or I can just change here on github in my branch?

**Comment by e-caste** [comment]
@itIsJim you can push new commits directly to your branch and the PR will update automatically.

**Comment by itIsJim** [comment]
I have pushed the correct version

**Comment by e-caste** [comment]
@itIsJim it looks much cleaner! Just one last thing: could you remove the bounce of the p (which goes right-left-right)?

**Comment by itIsJim** [comment]
ok, I will work on that 👌

**Comment by itIsJim** [comment]
new push on branch:Jim
logo animation fix(animation of P)/ translation-revision and todos (skeeelled and footer)

**Pull request merged**
